name: Backend CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: lint-and-test (py311)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements.txt - r requirements-dev.txt
      - name: Lint
        run: |
          black --check .
          isort --check-only .
          flake8
          mypy backend
      - name: Test
        run: |
          pytest -q --cov=backend --cov-report=xml
      - name: Security (bandit)
        run: |
          bandit -r backend -q || true
      - name: Security (pip-audit)
        run: |
          if [ -f requirements.txt ]; then pip-audit -r requirements.txt || true; else echo "no requirements.txt"; fi
