name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Show Python info
        run: |
          python -V
          pip -V

      - name: Install dependencies
        run: |
          if [ -f "backend/requirements.txt" ]; then
            pip install -r backend/requirements.txt
          fi
          pip install pytest httpx

      - name: "Run pytest (stable suite: devices delete + risk e2e fast)"
        run: |
          pytest -q tests/test_devices_delete.py tests/test_risk_engine_e2e.py -k "not test_restore_after_cooldown_and_low"

      - name: "Upload pytest cache (optional)"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-cache
          path: |
            .pytest_cache
            **/.pytest_cache
          if-no-files-found: ignore