name: Container Security

on:
  pull_request:
  push:
    branches: [main]

jobs:
  container-security:
    if: hashFiles('backend/Dockerfile') != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hadolint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile
      - name: Build image
        run: docker build -t iot-zero-trust/backend:ci -f backend/Dockerfile .
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: iot-zero-trust/backend:ci
          format: table
          exit-code: "0"
          ignore-unfixed: true